require('plugin-settings.telescope')
require('plugin-settings.floaterm')
require('plugin-settings.startify')
require('plugin-settings.jdtls_config')
require('plugin-settings.compe-config')
-- require('plugin-settings.norcalli_snippets')
-- require('plugin-settings.nvim-pairs')
